services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: PostgresSQLDatabase
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Ofernandoavila.FoodDelivery.Api
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT}
    command: ["dotnet", "Ofernandoavila.FoodDelivery.Api.dll"]